### ISSUE TITLE
Brake and Accelerator Pressed Simultaneously 

### ISSUE THREAD

**Issue by atokosch** [smit-happens/YCP_EVOS#106]
## End goal
If need to worry about brake and accel pedal being pressed at same time, maybe use an interrupt for brake so that way it stops receiving input from accel pedal. 

## Relevant Info/Links
#75 gas pedal
Possibly #25 

## Questions
Need to verify that is the brake and pedal are pressed at the same time then it can possibly stall the motor. I know this is an issue with electric race carts, not sure it it will be an issue for us. Will look into with Unitek. Also, this may not be an issue with we declare that you need to only use one foot with the left foot not being used at all.

**Comment by smit-happens** [comment]
This won't be accomplished for MS2 but it's something to be decided on for MS3

**Comment by smit-happens** [comment]
This is fixed
