### ISSUE TITLE
Precharge start signal

### ISSUE THREAD

**Issue by smit-happens** [smit-happens/YCP_EVOS#123]
## End goal
Enable the precharge start signal at the start of precharge stage

## Relevant Info/Links
I believe this has to be held high for the duration of driving @atokosch please verify

**Comment by atokosch** [comment]
@smit-happens You are correct, this signal needs to be held high for the duration of the drive. If this signal goes low, then the Drive signal also needs to go low. But if the Drive signal goes low, then precharge does not need to go low.

**Comment by atokosch** [comment]
Got this working. Need to verify with Teensy and TSCB.
