### ISSUE TITLE
Gas Pedal Tolerance

### ISSUE THREAD

**Issue by YoungMaker** [smit-happens/YCP_EVOS#130]
## End goal
Filter out noise in the gas pedal input so that you're not constantly sending accelerate commands to the Unitek

## Relevant Info/Links
The gas pedal input drifting slightly shouldn't cause any unintended acceleration.

**Comment by smit-happens** [comment]
Needs to account for the fractional percent that's being sent hen we are at 0

**Comment by smit-happens** [comment]
we still have to configure this based on the position of the potentiometers in the car

**Comment by PatHock** [comment]
Added 1uF capacitors to the analog inputs on the main brain PCB, for the accelerator and brake pedals. Noise is mostly eliminated, though there is slight flickering on the brake light, with threshold of 3%. Wiggling the pedal without engaging the brakes is enough to turn the brake light on and off.

**Comment by smit-happens** [comment]
fixed in 989b98888e6be2c0761601dfe5ad5beaa7ada736
