### ISSUE TITLE
Multiple task flags going off for buttons

### ISSUE THREAD

**Issue by smit-happens** [smit-happens/YCP_EVOS#135]
## End goal
Fix the buttons triggering multiple task flags

## Relevant Info/Links
 - Whenever a button is pressed, it will sometimes trigger multiple task flags
 - need to check with a scope first to verify hardware works

**Comment by smit-happens** [comment]
Probed with scope, found that pressing one button will cause a spike to occur on another line.

Shown below is a spike above `HIGH` signal voltage level occurring on a button line that wasn't pressed: ![button_spike](https://user-images.githubusercontent.com/4438744/37792208-868eb79e-2de1-11e8-8f16-cfc7912d9230.png)

**Comment by smit-happens** [comment]
@PatHock is fixing this, he'll close it when it's done

**Comment by PatHock** [comment]
Fixed in hardware. Button bouncing caused crosstalk, which has been minimized by addressing the bouncing issue.
