### ISSUE TITLE
Check datatypes to verify they are not the cause of the motor going in reverse

### ISSUE THREAD

**Issue by ShawnPierpont** [smit-happens/YCP_EVOS#144]
Check UnitekController and PedalController for datatype errors that could cause the car to receive the wrong direction for the motor to spin.

## End goal 
The datatypes have all been checked to verify they are not sending the message in the wrong format (uint vs int) where this could change the sign

**Comment by smit-happens** [comment]
@ShawnPierpont close and explain if needed
