### ISSUE TITLE
GLV Battery Voltage Too Low Notification

### ISSUE THREAD

**Issue by atokosch** [smit-happens/YCP_EVOS#145]
## End goal
Notify driver in more than one way than on the GLCD that the GLV batteries are running low. 

## Relevant Info/Links
Related to #95 #121

**Comment by atokosch** [comment]
Look up table for 24 = 2.8v, etc.. 
Test with power supply and get readings

**Comment by atokosch** [comment]
Unassigned others to show that I will implement this.

**Comment by smit-happens** [comment]
duplicate of #95
