### ISSUE TITLE
Energized doesn't get fully cleared off the screen

### ISSUE THREAD

**Issue by YoungMaker** [smit-happens/YCP_EVOS#172]
The last `e` in energized does not get fully cleared. 

The erase box is too small for the new larger font. 

```c++
 display->drawBox(MODE_START_X, MODE_START_Y-48, 50, 52);
```
a width > 50 should be applied

**Comment by smit-happens** [comment]
fixed in 41f67b67c586f991dd6bbe2af76f5fd77f294ad6
