### ISSUE TITLE
Gas Pedal polling

### ISSUE THREAD

**Issue by smit-happens** [smit-happens/YCP_EVOS#25]
Involves working on the PedalController to use the GasPedal Model to grab the analog value and store it in the model

**Comment by smit-happens** [comment]
implemented the model for this, need to work on the controller, StageManager, and main to finish this up

**Comment by PatHock** [comment]
We can either use a lookup table to correlate the linear and logarithmic pots, or we can calculate the pedal position using an equation that represents the "curves" for each potentiometer. The Teensy 3.6 has a floating point unit which will facilitate floating point calculations, making the calculation option practical.

If calculations are to be used (or even the lookup table), we need to choose our potentiometers soon.

**Comment by PatHock** [comment]
EV 3.5.4
All acceleration control signals (between the accelerator pedal and the motor controller) must
have error checking.
For analog acceleration control signals, this error checking must detect open circuit, short to
ground and short to sensor power.

**There is no mention of using both linear and logarithmic pots in the Hybrid Rules**
