### ISSUE TITLE
90% Precharge setting in Unitek

### ISSUE THREAD

**Issue by smit-happens** [smit-happens/YCP_EVOS#29]
Correlates to #28 where we only have to have CAN TX working for the Unitek.

It would be beneficial to get CAN RX working, and that may be a side effect of CAN RX with Orion #30, but for now Priority for CAN Unitek is TX before RX

**Comment by JoeMaier** [comment]
![20180312_134038](https://user-images.githubusercontent.com/35609264/37380136-8a688d52-270d-11e8-9174-649a94b68be7.jpg)
