### ISSUE TITLE
Orion battery level reading (CAN TX/RX)

### ISSUE THREAD

**Issue by smit-happens** [smit-happens/YCP_EVOS#30]
We need to request and receive the battery level from Orion in order to store the 90% level in unitek as described in #29

**Comment by ShawnPierpont** [comment]
This is working using the FlexCAN library and the OrionController and OrionModel have been implemented to extract the data from the CAN messages that have been designed that the BMS will output. The BMS does not need to be written to to receive this data, but rather just read for the specific CAN ID we need. That part will be implemented in the CanController and will just need to return the struct I created which is just using the data directly from the buffer of the CAN message
