### ISSUE TITLE
Request Unitek register read 

### ISSUE THREAD

**Issue by smit-happens** [smit-happens/YCP_EVOS#31]
We need a method to ask the Unitek to send back register data, this is somewhat implemented in 
```cpp
void CanController::sendUnitekRead(uint8_t regId, uint8_t pollTime = 0) {...}
```
There needs to be some support for using the CAN model to send the data out on the wire

**Comment by JoeMaier** [comment]
@smit-happens can you elaborate on this? I'm not sure what you mean by "There needs to be some support for using the CAN model to send the data out on the wire."
