### ISSUE TITLE
Unit testing structure

### ISSUE THREAD

**Issue by smit-happens** [smit-happens/YCP_EVOS#45]
Find the correct structure of unit testing that will work for EVOS in preparation for our sprints

### [platformio unit testing page](http://docs.platformio.org/en/latest/plus/unit-testing.html)

**Comment by smit-happens** [comment]
[Platformio Remote Unit testing example](https://github.com/platformio/platformio-remote-unit-testing-example)

**Comment by ShawnPierpont** [comment]
https://github.com/platformio/platformio-remote-unit-testing-example

**Comment by smit-happens** [comment]
this is like one commit away now that I ran some tests with the gaspedal model

**Comment by smit-happens** [comment]
The basic structure is there and working
