### ISSUE TITLE
Shutdown circuit integration with Main Brain

### ISSUE THREAD

**Issue by PatHock** [smit-happens/YCP_EVOS#50]
* Not priority for MS2
* BMS, IMD error LEDs on the dashboard should respond to appropriate error inputs from shutdown circuit (required for FSAE rule compliance)
* Putting the car into the shutdown stage could present some problems since the LEDs need to be updated

**Comment by smit-happens** [comment]
Accomplished in commit 649d929b82033ec451d809e597ffbc96b6950ccb
