### ISSUE TITLE
Implement get total voltage from batteries

### ISSUE THREAD

**Issue by JoeMaier** [smit-happens/YCP_EVOS#80]
## End goal
Implement getTotalVoltage() in Orion Model and getPackVoltage() in orionController. This will allow the 90% charge value to be set in Unitek MC

## Relavent Info/Links
In order to calculate and set the 90% charge the voltage of the batteries, returned from getPackVoltage(), needs to be a float value in volts.

**Comment by smit-happens** [comment]
More info from @ShawnPierpont:  "Using the CANController, OrionController and OrionModel, update the current state of charge of the battery pack based on the message received from the BMS"
