### ISSUE TITLE
GLV Battery Voltage too low

### ISSUE THREAD

**Issue by atokosch** [smit-happens/YCP_EVOS#95]
## End goal
Verify battery voltage is not too low before precharge, if not below threshold, allow precharge. If not, then don't allow precharge or transition to shutdown. 

## Relevant Info/Links
Related to #32 need to verify that GLV batteries are not below set voltage. 
Related to #92 if voltage gets too low, need to shutdown. 

## Questions
Interrupt driven?

**Comment by atokosch** [comment]
Related to #32 , need to verify that the GLV batteries are not below set voltage 
What is the lowest voltage we will run the pump? @smit-happens @PatHock 

Also related to #92 , if voltage gets too low, need to shutdown.

**Comment by smit-happens** [comment]
Not worrying about it
